apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - image: php
        name: php
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/
          name: php-claim0
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
status: {}
